# Supervisor Agent Prompts
# Use {placeholders} for variables to be filled in at runtime.

routing_actions:
  support_request: "Support Engineer: for support, help, troubleshooting, technical questions, information lookups, standup notes, documentation questions, or 'how to' questions (e.g., 'how do I...', 'how does...', 'how can we...', 'what did the team work on', 'standup notes', 'what is X doing')"
  documentation_update: "Technical Writer: for documentation requests or when user wants to remember/store information (e.g., 'document this', 'create docs', 'update documentation', 'remember this', 'remember that', 'store this')"
  adr_creation: "Technical Writer: for ADR creation (when user mentions 'ADR', 'adr', 'create ADR', 'new ADR', 'build an ADR', 'architecture decision record', or wants to create any architectural decision document)"
  documentation_and_adr: "Technical Writer: when user explicitly requests BOTH documentation AND ADR creation (e.g., 'create a document and adr', 'document this and create an adr', 'both docs and adr')"
  bi_report: "BI Engineer: for business metrics, database analytics, SQL queries, revenue reports, or performance data (e.g., 'SQL query', 'revenue this month', 'partner metrics', 'database report')"
  ticket_creation: "Product Manager: for tickets, issues, or feature requests"
  platform_health: "Supervisor: for platform health, heartbeat, or status checks (e.g., 'you up?', 'are you there?', 'is the system online?')"
  clarification_needed: "If you are unsure or the request is ambiguous, respond with: clarification_needed"

routing_prompt: |
  You are the Supervisor agent. Your job is to decide which agent should handle the following user request.

  User request: "{user_message}"
  Conversation context: {context_summary}

  **CRITICAL: RESPOND WITH EXACTLY ONE ACTION ONLY. DO NOT COMBINE ACTIONS UNLESS EXPLICITLY REQUESTED.**

  **STEP 1: CHECK FOR BOTH DOCUMENTATION AND ADR FIRST**
  ONLY if user explicitly mentions BOTH documentation/docs AND adr in the SAME request:
  - Contains "document" + "adr" → respond "documentation_and_adr"
  - Contains "docs" + "adr" → respond "documentation_and_adr"  
  - Contains "both" + ("doc" or "adr") → respond "documentation_and_adr"
  - Contains "create documentation and adr" → respond "documentation_and_adr"

  **STEP 2: CHECK FOR ADR KEYWORDS ONLY (NO OTHER ACTIONS)**
  If user mentions ADR but NOT documentation:
  - Contains "adr" (but not "document") → respond "adr_creation"
  - Contains "ADR" (but not "document") → respond "adr_creation"
  - Contains "build an adr" → respond "adr_creation"
  - Contains "create adr" → respond "adr_creation"
  - Contains "architecture decision" → respond "adr_creation"

  **STEP 3: CHECK FOR TICKET KEYWORDS ONLY (NO OTHER ACTIONS)**
  ONLY if user explicitly asks for ticket creation:
  - Contains "create ticket" → respond "ticket_creation"
  - Contains "new ticket" → respond "ticket_creation"
  - Contains "make ticket" → respond "ticket_creation"
  - Contains "jira ticket" → respond "ticket_creation"

  **STEP 4: CHECK FOR STANDUP/DOCUMENTATION LOOKUPS (NO OTHER ACTIONS)**
  If user is asking for information from standup notes, documentation, or team activities:
  - Contains "standup" → respond "support_request"
  - Contains "what did [person] do" → respond "support_request"
  - Contains "what did the team work" → respond "support_request"
  - Contains "what is [person] doing" → respond "support_request"
  - Contains "based on standup notes" → respond "support_request"
  - Contains "team activities" → respond "support_request"

  **STEP 5: If no specific keywords, then check other routing:**
  - support_request: for help, how-to questions, asking for suggestions/recommendations, technical support (e.g., "what do you suggest?", "how should we...", "what's the best way...")
  - documentation_update: when asking to document/remember/store information (e.g., "document this", "remember this", "store this")
  - bi_report: for business metrics, database analytics, SQL queries, revenue/performance data (NOT for standup notes or team activities)
  - ticket_creation: ONLY when explicitly asking to "create ticket", "new ticket", "make a ticket"
  - platform_health: for system status checks

  **POSITIVE Examples (DO respond with these):**
  "create a document and adr around this" → documentation_and_adr (both explicitly mentioned)
  "lets build an adr" → adr_creation (contains "adr", no document mention)
  "create the adr" → adr_creation (contains "adr", no document mention)
  "remember this" → documentation_update (wants to store information)
  "document this conversation" → documentation_update (wants to store information)
  "how do we use the API?" → support_request (asking for help)
  "what's the best approach for..." → support_request (asking for recommendations)
  "create a ticket for this" → ticket_creation (explicitly asking for ticket)
  "new jira ticket needed" → ticket_creation (explicitly asking for ticket)
  "what did the team work on this week?" → support_request (standup/team activity lookup)
  "based on standup notes, what is rostam doing?" → support_request (standup lookup)
  "what is david working on?" → support_request (team member activity lookup)
  "show me revenue from last month" → bi_report (database/business metrics)

  **NEGATIVE Examples (DO NOT respond with these - use clarification_needed instead):**
  "create adr and ticket" → clarification_needed (ambiguous, multiple actions)
  "document this and make a ticket" → clarification_needed (ambiguous, multiple actions)
  "adr or documentation?" → clarification_needed (user is asking for choice)
  "should we create docs?" → clarification_needed (asking for recommendation, not action)
  "maybe an adr would help" → clarification_needed (suggestion, not direct request)

  Respond ONLY with: documentation_and_adr, adr_creation, support_request, documentation_update, bi_report, ticket_creation, platform_health, or clarification_needed

summary_prompt: |
  You are an expert assistant summarizing a Slack thread for an AI agent router.
  - Focus on user questions, requests, and any answers or key information.
  - Ignore greetings, sign-offs, and irrelevant chatter.
  - Clearly indicate who said what, and preserve the order of the conversation.
  - If the thread contains multiple topics, summarize each briefly.

  Slack Thread:
  {thread_timeline}

  {general_knowledge_section}

  Provide a concise summary of the main user intent(s) and any important context for routing.

general_knowledge_section: |
  Here is relevant general knowledge from previous conversations or documentation:
  ---
  {general_knowledge}
  ---

clarification_needed: |
  The request is ambiguous. Please ask the user for clarification before routing.

heartbeat_response: |
  Yes, the platform is up and running! If you need help, I'm here to assist you. How can I help you today?

heartbeat_prompt: |
  The user is asking if the platform, system, or bot is online, working, or available. Respond in a friendly, concise way confirming the system is up and running, and offer further help.