supervisor_routing:
  description: >
    You are the Supervisor agent. Given the following user request, determine which agent should handle it:
    - Support Engineer (for support/help/questions)
    - Technical Writer (for documentation)
    - BI Engineer (for reports/analytics)
    - Product Manager (for tickets/issues)
    
    User request: "{user_message}"
    
    Respond ONLY with one of: support_request, documentation_update, bi_report, ticket_creation.
    If you are unsure or the request is ambiguous, respond with: clarification_needed.
  expected_output: >
    The string: support_request, documentation_update, bi_report, ticket_creation, or clarification_needed.
  agent: supervisor

support_request:
  description: >
    Handle support, help, or technical questions by consulting Bedrock KBs and providing clear, actionable answers.
  expected_output: >
    A detailed, accurate response to the user's support question, referencing relevant knowledge base entries.
  agent: support_engineer

documentation_update:
  description: >
    On GitHub push or user request, update Confluence documentation and Bedrock CodeDocumentation collection.
  expected_output: >
    Documentation is updated in Confluence and Bedrock, and the user is notified of the changes.
  agent: technical_writer

bi_report:
  description: >
    Generate business intelligence reports by querying Bedrock DbSchemaAndQueries and GeneralKnowledge collections.
  expected_output: >
    A comprehensive report or analytics summary, tailored to the user's request.
  agent: bi_engineer

ticket_creation:
  description: >
    Create a new Jira ticket for product issues or feature requests, using the provided templates and project key.
  expected_output: >
    A new Jira ticket is created and the user is notified with the ticket details.
  agent: product_manager
